import {
  readFileSync,
  readdirSync,
  mkdirSync,
  writeFileSync,
  unlinkSync,
  type Dirent,
} from "node:fs";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

export const GENERATED_MARKER =
  "<!-- Generated by sync-plans; do not edit. -->";
export const INDEX_FILENAME = "index.md";
const WORKSPACE_ROOT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../..",
);

export const TASK_STATES = [
  "PROPOSED",
  "PENDING",
  "IN_PROGRESS",
  "IMPLEMENTED",
  "MERGING",
  "QUEUED",
  "MERGED",
  "CANCELLED",
  "MAIN_PENDING",
  "MAIN_IN_PROGRESS",
  "MAIN_IMPLEMENTED",
] as const;

export type TaskState = (typeof TASK_STATES)[number];

export interface TaskExportItem {
  taskRef: string;
  title: string;
  state: TaskState;
  updatedAt: string;
  description?: string;
  dependsOn?: string[];
  followUpCategory?: string;
  createdAt?: string;
  proposedFromRef?: string;
  artifactKinds?: string[];
}

export interface TaskExport {
  tasks: TaskExportItem[];
}

export interface SyncResult {
  added: string[];
  updated: string[];
  /** All generated files that differ from the current mirror. */
  written: string[];
  removed: string[];
  unchanged: string[];
}

const STATUS_ORDER = [
  "Drafts",
  "Active",
  "Ready",
  "Merging",
  "Merged",
  "Archived",
] as const;
const STATUS_MEANINGS: Record<(typeof STATUS_ORDER)[number], string> = {
  Drafts: "Suggested work that has not been accepted",
  Active: "Accepted work waiting to start or in progress",
  Ready: "Completed work ready for merge",
  Merging: "Work queued for or currently in merge",
  Merged: "Finished and merged work",
  Archived: "Abandoned work",
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function requiredString(
  value: unknown,
  field: string,
  taskNumber: number,
): string {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`tasks[${taskNumber}].${field} must be a non-empty string`);
  }
  return value;
}

function optionalString(
  value: unknown,
  field: string,
  taskNumber: number,
): string | undefined {
  if (value === undefined || value === null) return undefined;
  return requiredString(value, field, taskNumber);
}

function validateIsoDate(
  value: unknown,
  field: string,
  taskNumber: number,
): string {
  const date = requiredString(value, field, taskNumber);
  if (Number.isNaN(Date.parse(date))) {
    throw new Error(
      `tasks[${taskNumber}].${field} must be an ISO-8601 timestamp`,
    );
  }
  return date;
}

function validateRef(
  value: unknown,
  field: string,
  taskNumber: number,
): string {
  const ref = requiredString(value, field, taskNumber);
  if (!/^#?\d+$/.test(ref)) {
    throw new Error(
      `tasks[${taskNumber}].${field} must be a task reference such as "#12"`,
    );
  }
  return ref;
}

function validateStringArray(
  value: unknown,
  field: string,
  taskNumber: number,
): string[] {
  if (
    !Array.isArray(value) ||
    value.some((item) => typeof item !== "string" || item.trim() === "")
  ) {
    throw new Error(
      `tasks[${taskNumber}].${field} must be an array of non-empty strings`,
    );
  }
  return [...value];
}

function canonicalRef(ref: string): string {
  return ref.replace(/^#/, "");
}

export function statusLabel(state: TaskState): (typeof STATUS_ORDER)[number] {
  switch (state) {
    case "PROPOSED":
      return "Drafts";
    case "PENDING":
    case "IN_PROGRESS":
    case "MAIN_PENDING":
    case "MAIN_IN_PROGRESS":
      return "Active";
    case "IMPLEMENTED":
    case "MAIN_IMPLEMENTED":
      return "Ready";
    case "MERGING":
    case "QUEUED":
      return "Merging";
    case "MERGED":
      return "Merged";
    case "CANCELLED":
      return "Archived";
  }
}

export function slugifyTaskTitle(title: string): string {
  const slug = title
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80)
    .replace(/-+$/g, "");
  return slug || "untitled";
}

export function taskFilename(task: Pick<TaskExportItem, "taskRef">): string {
  return `task-${canonicalRef(task.taskRef).padStart(3, "0")}.md`;
}

export function validateTaskExport(input: unknown): TaskExport {
  if (!isRecord(input) || !Array.isArray(input.tasks)) {
    throw new Error('task export must be a JSON object with a "tasks" array');
  }

  const refs = new Set<string>();
  const tasks = input.tasks.map((rawTask, taskNumber): TaskExportItem => {
    if (!isRecord(rawTask)) {
      throw new Error(`tasks[${taskNumber}] must be an object`);
    }

    const taskRef = validateRef(rawTask.taskRef, "taskRef", taskNumber);
    const refKey = canonicalRef(taskRef);
    if (refs.has(refKey)) {
      throw new Error(
        `tasks[${taskNumber}].taskRef duplicates task reference "${taskRef}"`,
      );
    }
    refs.add(refKey);

    const title = requiredString(rawTask.title, "title", taskNumber);
    const state = requiredString(
      rawTask.state,
      "state",
      taskNumber,
    ) as TaskState;
    if (!TASK_STATES.includes(state)) {
      throw new Error(
        `tasks[${taskNumber}].state "${String(rawTask.state)}" is unsupported; expected one of ${TASK_STATES.join(", ")}`,
      );
    }

    const task: TaskExportItem = {
      taskRef,
      title,
      state,
      updatedAt: validateIsoDate(rawTask.updatedAt, "updatedAt", taskNumber),
    };

    if (rawTask.description !== undefined && rawTask.description !== null) {
      if (typeof rawTask.description !== "string") {
        throw new Error(
          `tasks[${taskNumber}].description must be a string when supplied`,
        );
      }
      task.description = rawTask.description;
    }
    if (rawTask.dependsOn !== undefined) {
      task.dependsOn = validateStringArray(
        rawTask.dependsOn,
        "dependsOn",
        taskNumber,
      );
    } else {
      task.dependsOn = [];
    }
    if (
      rawTask.followUpCategory !== undefined &&
      rawTask.followUpCategory !== null
    ) {
      task.followUpCategory = requiredString(
        rawTask.followUpCategory,
        "followUpCategory",
        taskNumber,
      );
    }
    if (rawTask.createdAt !== undefined && rawTask.createdAt !== null) {
      task.createdAt = validateIsoDate(
        rawTask.createdAt,
        "createdAt",
        taskNumber,
      );
    }
    if (
      rawTask.proposedFromRef !== undefined &&
      rawTask.proposedFromRef !== null
    ) {
      task.proposedFromRef = validateRef(
        rawTask.proposedFromRef,
        "proposedFromRef",
        taskNumber,
      );
    }
    if (rawTask.artifactKinds !== undefined) {
      task.artifactKinds = validateStringArray(
        rawTask.artifactKinds,
        "artifactKinds",
        taskNumber,
      );
    } else {
      task.artifactKinds = [];
    }
    return task;
  });

  return {
    tasks: tasks.sort(
      (left, right) =>
        Number(canonicalRef(left.taskRef)) -
        Number(canonicalRef(right.taskRef)),
    ),
  };
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function yamlArray(values: string[]): string {
  return JSON.stringify(values);
}

function frontmatter(task: TaskExportItem): string {
  const lines = [
    "---",
    `taskRef: ${yamlString(task.taskRef)}`,
    `title: ${yamlString(task.title)}`,
    `state: ${yamlString(task.state)}`,
    `status: ${yamlString(statusLabel(task.state))}`,
    `dependsOn: ${yamlArray(task.dependsOn ?? [])}`,
    `followUpCategory: ${task.followUpCategory === undefined ? "null" : yamlString(task.followUpCategory)}`,
    `lastUpdated: ${yamlString(task.updatedAt)}`,
    `createdAt: ${task.createdAt === undefined ? "null" : yamlString(task.createdAt)}`,
    `proposedFromRef: ${task.proposedFromRef === undefined ? "null" : yamlString(task.proposedFromRef)}`,
    `artifactKinds: ${yamlArray(task.artifactKinds ?? [])}`,
    "---",
  ];
  return lines.join("\n");
}

export function renderTaskDocument(task: TaskExportItem): string {
  const description = task.description?.trim();
  const body = description || `# ${task.title}`;
  return `${frontmatter(task)}\n\n${GENERATED_MARKER}\n\n${body}\n`;
}

function markdownCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function taskRefNumber(task: TaskExportItem): number {
  return Number(canonicalRef(task.taskRef));
}

export function renderIndex(tasks: TaskExportItem[]): string {
  const lines = [
    GENERATED_MARKER,
    "# Project plans",
    "",
    "> Generated from a task-board export. Do not edit generated files; `docs/plans/recovered-task-export.v1.json` is the tracked recovery input until a newer explicit board export is imported.",
    "",
    "## Summary",
    "",
    "| Status | Tasks | Meaning |",
    "| --- | ---: | --- |",
  ];

  for (const status of STATUS_ORDER) {
    const count = tasks.filter(
      (task) => statusLabel(task.state) === status,
    ).length;
    lines.push(`| ${status} | ${count} | ${STATUS_MEANINGS[status]} |`);
  }

  for (const status of STATUS_ORDER) {
    const grouped = tasks
      .filter((task) => statusLabel(task.state) === status)
      .sort((left, right) => taskRefNumber(left) - taskRefNumber(right));
    lines.push("", `## ${status} (${grouped.length})`, "");
    if (grouped.length === 0) {
      lines.push("No tasks.");
      continue;
    }
    lines.push(
      "| Ref | Title | Follow-up | Dependencies | Last updated |",
      "| --- | --- | --- | --- | --- |",
    );
    for (const task of grouped) {
      const dependencies = task.dependsOn?.length
        ? task.dependsOn.join(", ")
        : "—";
      const followUp = task.followUpCategory ?? "—";
      lines.push(
        `| [${markdownCell(task.taskRef)}](./${taskFilename(task)}) | ${markdownCell(task.title)} | ${markdownCell(followUp)} | ${markdownCell(dependencies)} | ${markdownCell(task.updatedAt)} |`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

function isGeneratedFile(content: string): boolean {
  return (
    content.startsWith(`${GENERATED_MARKER}\n`) ||
    content.includes(`\n${GENERATED_MARKER}\n`)
  );
}

function writeIfChanged(
  path: string,
  content: string,
  result: SyncResult,
  write: boolean,
): void {
  let existing: string | undefined;
  try {
    existing = readFileSync(path, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing === content) {
    result.unchanged.push(basename(path));
    return;
  }
  const filename = basename(path);
  if (existing === undefined) {
    result.added.push(filename);
  } else {
    result.updated.push(filename);
  }
  if (write) writeFileSync(path, content, "utf8");
  result.written.push(filename);
}

export function syncPlans(
  tasks: TaskExportItem[],
  outputDir: string,
  options: { preview?: boolean } = {},
): SyncResult {
  const write = !options.preview;
  if (write) mkdirSync(outputDir, { recursive: true });
  const result: SyncResult = {
    added: [],
    updated: [],
    written: [],
    removed: [],
    unchanged: [],
  };
  const generated = new Map<string, string>();
  for (const task of tasks) {
    generated.set(taskFilename(task), renderTaskDocument(task));
  }
  generated.set(INDEX_FILENAME, renderIndex(tasks));

  let entries: Dirent[];
  try {
    entries = readdirSync(outputDir, { withFileTypes: true });
  } catch (error) {
    if (
      !write &&
      error instanceof Error &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      entries = [];
    } else {
      throw error;
    }
  }
  for (const [filename, content] of generated) {
    writeIfChanged(resolve(outputDir, filename), content, result, write);
  }

  for (const entry of entries) {
    if (
      !entry.isFile() ||
      !entry.name.endsWith(".md") ||
      generated.has(entry.name)
    )
      continue;
    const path = resolve(outputDir, entry.name);
    let content: string;
    try {
      content = readFileSync(path, "utf8");
    } catch {
      continue;
    }
    if (isGeneratedFile(content)) {
      if (write) unlinkSync(path);
      result.removed.push(entry.name);
    }
  }

  result.added.sort();
  result.updated.sort();
  result.written.sort();
  result.removed.sort();
  result.unchanged.sort();
  return result;
}

export function syncPlansFromJson(
  json: string,
  outputDir: string,
  options: { preview?: boolean } = {},
): SyncResult {
  let input: unknown;
  try {
    input = JSON.parse(json) as unknown;
  } catch (error) {
    throw new Error(
      `task export is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const exportData = validateTaskExport(input);
  return syncPlans(exportData.tasks, outputDir, options);
}

export function previewPlans(
  tasks: TaskExportItem[],
  outputDir: string,
): SyncResult {
  return syncPlans(tasks, outputDir, { preview: true });
}

export function previewPlansFromJson(
  json: string,
  outputDir: string,
): SyncResult {
  return syncPlansFromJson(json, outputDir, { preview: true });
}

function readInput(inputPath: string): string {
  return inputPath === "-"
    ? readFileSync(0, "utf8")
    : readFileSync(resolve(WORKSPACE_ROOT, inputPath), "utf8");
}

function usage(): string {
  return [
    "Usage: npx tsx scripts/replit-plan-sync/task-plan-sync.ts --input <task-export.json> [--output <directory>] [--preview]",
    "",
    "Use --input - to read the JSON export from standard input.",
    "The default output directory is docs/plans.",
    "Use --preview (or --dry-run) to report changes without writing the mirror.",
  ].join("\n");
}

function parseArgs(args: string[]): {
  input: string;
  output: string;
  preview: boolean;
} {
  let input = "-";
  let output = resolve(WORKSPACE_ROOT, "docs/plans");
  let preview = false;
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--") continue;
    if (arg === "--help" || arg === "-h") {
      console.log(usage());
      process.exitCode = 0;
      return { input, output, preview };
    }
    if (arg === "--input") {
      const value = args[index + 1];
      if (!value) throw new Error("--input requires a file path or -");
      input = value;
      index += 1;
      continue;
    }
    if (arg === "--output") {
      const value = args[index + 1];
      if (!value) throw new Error("--output requires a directory path");
      output = resolve(WORKSPACE_ROOT, value);
      index += 1;
      continue;
    }
    if (arg === "--preview" || arg === "--dry-run") {
      preview = true;
      continue;
    }
    throw new Error(`unknown argument "${arg}"\n\n${usage()}`);
  }
  return { input, output, preview };
}

export function main(args = process.argv.slice(2)): void {
  try {
    const { input, output, preview } = parseArgs(args);
    if (
      process.exitCode === 0 &&
      args.some((arg) => arg === "--help" || arg === "-h")
    )
      return;
    const result = syncPlansFromJson(readInput(input), output, { preview });
    const verb = preview ? "Previewed" : "Synced";
    console.log(
      `${verb} task-plan mirror at ${output}: ${result.added.length} added, ${result.updated.length} updated, ${result.removed.length} removed, ${result.unchanged.length} unchanged.`,
    );
    for (const [label, files] of [
      ["Added", result.added],
      ["Updated", result.updated],
      ["Removed", result.removed],
      ["Unchanged", result.unchanged],
    ] as const) {
      if (files.length > 0) console.log(`${label}: ${files.join(", ")}`);
    }
    if (preview) console.log("Preview only; no files were written.");
  } catch (error) {
    console.error(
      `sync-plans: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exitCode = 1;
  }
}

if (resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) {
  main();
}
