// Provider-agnostic companion reconciliation (EH-Q1) - synthetic only
export const VERIFICATION_STATES = ["SNAPSHOT","LIVE_VERIFIED","STALE","CLOSED","BLOCKED","UNKNOWN"] as const;
export const EXECUTION_STATES = ["READY_TO_APPLY","FILLED","AWAITING_OPERATOR","BLOCKED","SUBMITTED"] as const;
export const CHANNELS = ["web_form","email","external_provider"] as const;
export const QUALIFYING_KINDS = new Set(["submission_receipt","confirmation","correspondence"]);
export const RECONCILIATION_SCHEMA = "escapehatch/application-companion-reconciliation-result/v1";
export type VerificationState = typeof VERIFICATION_STATES[number];
export type ExecutionState = typeof EXECUTION_STATES[number];
export type Channel = typeof CHANNELS[number];
export type CareerState = { schema_version:string; state_id:string; revision:number; updated_at:string; profile:unknown; opportunities:Array<{id:string; verification?:{state:VerificationState; verified_at:string; detail?:string; source?:string}; [k:string]:unknown}>; applications:Array<{id:string; opportunity_id:string; resume_id:string; status:string; submitted_at:string|null; external_reference?:string|null; execution?:{state:ExecutionState; channel:Channel; last_transition_at:string; evidence_id?:string; block_reason?:string; awaiting_reason?:string; detail?:string}; [k:string]:unknown}>; evidence:Array<{id:string; application_id:string; kind:string; artifact:{owner:string; kind:string; locator:string}; observed_at:string}>; [k:string]:unknown };
export type ProviderOpportunity = { opportunity_id:string; verification?:{state:VerificationState; verified_at:string; detail?:string; source?:string}; auth?:{authorized:boolean; reason?:string} };
export type ProviderApplication = { application_id:string; opportunity_id?:string; execution?:{state:ExecutionState; channel:Channel; last_transition_at:string; evidence_id?:string}; evidence?:Array<{id:string; kind:string; artifact?:unknown; observed_at:string}>; mail?:{draft:boolean; sent:boolean; provider_confirmation?:string; outbox?:boolean}; auth?:{authorized:boolean; channel?:string; reason?:string}; operator_confirmed?:boolean };
export type ProviderSnapshot = { observed_at:string; provider_id:string; read_back:boolean; opportunities?:ProviderOpportunity[]; applications?:ProviderApplication[] };
export type FreshnessTransition = { opportunity_id:string; from:VerificationState|null; to:VerificationState|null; queue_active:boolean; history_preserved:boolean };
export type ExecutionTransition = { application_id:string; from:ExecutionState|null; to:ExecutionState|null; evidence_binding:"local"|"provider"|"operator_confirmed"|"none"; conflict_preserved:boolean; reason:string };
export type ReconciliationResult = { schema:typeof RECONCILIATION_SCHEMA; reconciled_at:string; provider_read_back:boolean; freshness_transition:FreshnessTransition[]; execution_transition:ExecutionTransition[]; evidence_binding:"local"|"provider"|"operator_confirmed"|"none"; conflict_preserved:boolean; queue_active:Record<string,boolean>; history_preserved:boolean; idempotent:boolean };
function deepClone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}
function isDateTime(s:string){try{const v=s.endsWith("Z")?s:s.replace("Z","+00:00");return !Number.isNaN(Date.parse(v));}catch{return false;}}
function qualifyingEvidenceForApp(ev:CareerState["evidence"],appId:string){return ev.filter(e=>e.application_id===appId && QUALIFYING_KINDS.has(e.kind));}
export function reconcile(careerState:CareerState, providerSnapshot:ProviderSnapshot|null|undefined):{reconciledState:CareerState; result:ReconciliationResult}{
  const now=new Date().toISOString(); const reconciledState=deepClone(careerState); const providerReadBack=Boolean(providerSnapshot && providerSnapshot.read_back===true);
  const freshness:FreshnessTransition[]=[]; const execution:ExecutionTransition[]=[]; let anyConflict=false; const queueActive:Record<string,boolean>={}; const historyPreserved=true;
  const oppById=new Map(reconciledState.opportunities.map(o=>[o.id,o])); const providerOppMap=new Map<string,ProviderOpportunity>(); for(const po of providerSnapshot?.opportunities||[]) providerOppMap.set(po.opportunity_id,po);
  const providerAppMap=new Map<string,ProviderApplication>(); for(const pa of providerSnapshot?.applications||[]) providerAppMap.set(pa.application_id,pa);
  for(const opp of reconciledState.opportunities){
    const from=(opp.verification?.state as VerificationState)??null; const providerOpp=providerOppMap.get(opp.id); let to:VerificationState|null=from; let active=true; let history=true;
    if(!providerReadBack){to=from; if(["STALE","CLOSED"].includes(from as string)) active=false; else if(["BLOCKED","UNKNOWN","SNAPSHOT"].includes(from as string)) active=false; else if(from==="LIVE_VERIFIED") active=true; else active=false;
    }else if(!providerOpp||!providerOpp.verification){to=from; if(["STALE","CLOSED"].includes(from as string)) active=false; else if(from==="LIVE_VERIFIED") active=true; else active=false;
    }else{const pv=providerOpp.verification; if(!VERIFICATION_STATES.includes(pv.state as VerificationState)||!isDateTime(pv.verified_at)){to=from; active=from==="LIVE_VERIFIED";
      }else if(pv.state==="LIVE_VERIFIED"){to="LIVE_VERIFIED"; active=true; opp.verification={state:"LIVE_VERIFIED",verified_at:pv.verified_at,detail:pv.detail??"Live posting re-observed via provider read-back",source:pv.source??providerSnapshot!.provider_id};
      }else if(["STALE","CLOSED"].includes(pv.state)){to=pv.state as VerificationState; active=false; opp.verification={state:pv.state as VerificationState,verified_at:pv.verified_at,detail:pv.detail??`Provider reports ${pv.state}`,source:pv.source??providerSnapshot!.provider_id};
      }else if(pv.state==="BLOCKED"){to="BLOCKED"; active=false; opp.verification={state:"BLOCKED",verified_at:pv.verified_at,detail:pv.detail??"Provider authorization blocked",source:pv.source??providerSnapshot!.provider_id};
      }else if(["UNKNOWN","SNAPSHOT"].includes(pv.state)){to=from; if(from==="LIVE_VERIFIED"&&pv.state==="UNKNOWN") anyConflict=true; active=to==="LIVE_VERIFIED";}
    }
    queueActive[opp.id]=active; freshness.push({opportunity_id:opp.id,from,to,queue_active:active,history_preserved:history});
  }
  for(const app of reconciledState.applications){
    const from=(app.execution?.state as ExecutionState)??null; const fromChannel=(app.execution?.channel as Channel)??"web_form"; const oppId=app.opportunity_id; const opp=oppById.get(oppId);
    const oppVerification=opp?.verification?.state as VerificationState|undefined; const providerApp=providerAppMap.get(app.id);
    let to:ExecutionState|null=from; let evidenceBinding:ExecutionTransition["evidence_binding"]="none"; let conflict=false; let reason="no_change";
    const localQual=qualifyingEvidenceForApp(reconciledState.evidence,app.id); const hasLocalQual=localQual.length>0;
    const providerQual=providerApp?.evidence?.filter(e=>QUALIFYING_KINDS.has(e.kind))||[]; const hasProviderQual=providerQual.length>0;
    const localAny=reconciledState.evidence.filter(e=>e.application_id===app.id); const hasAnyLocal=localAny.length>0; const providerAny=providerApp?.evidence||[]; const hasAnyProvider=providerAny.length>0;
    if(!providerReadBack){to=from; evidenceBinding=hasAnyLocal?"local":"none"; reason="provider_read_back_required";
    }else if(!providerApp){to=from; evidenceBinding=hasAnyLocal?"local":"none"; reason="no_provider_application_snapshot"; if(["STALE","CLOSED"].includes(oppVerification as string)&&["READY_TO_APPLY","FILLED"].includes(from as string)){to="BLOCKED"; reason=`posting_${oppVerification}_deactivates_queue`; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason=`posting_${oppVerification}_without_erasing_history`; app.execution.last_transition_at=now;}else app.execution={state:"BLOCKED",channel:fromChannel,last_transition_at:now,block_reason:`posting_${oppVerification}` as string};}
    }else{
      const authFailure=providerApp.auth&&providerApp.auth.authorized===false; const oppAuthFailure=providerOppMap.get(oppId)?.auth?.authorized===false;
      if(authFailure||oppAuthFailure){
        if(from==="SUBMITTED"){conflict=true; anyConflict=true; to="BLOCKED"; evidenceBinding=hasAnyLocal?"local":"none"; reason="provider_authorization_failure_BLOCKED"; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason=providerApp.auth?.reason||"provider_authorization_failure"; app.execution.last_transition_at=now;}
        }else{if(["READY_TO_APPLY","FILLED","AWAITING_OPERATOR","BLOCKED"].includes(from as string)){const ch=app.execution?.channel??providerApp.auth?.channel as Channel??fromChannel; if(ch==="email"){to="AWAITING_OPERATOR"; reason="provider_authorization_failure_AWAITING_OPERATOR"; if(app.execution){app.execution.state="AWAITING_OPERATOR"; app.execution.awaiting_reason="provider_authorization_failure"; app.execution.last_transition_at=now;}}else{to="BLOCKED"; reason="provider_authorization_failure_BLOCKED"; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason=providerApp.auth?.reason||"provider_authorization_failure"; app.execution.last_transition_at=now;}} evidenceBinding=hasAnyProvider?"provider":hasAnyLocal?"local":"none";}}
      }else{
        const providerFreshness=providerOppMap.get(oppId)?.verification?.state??oppVerification;
        if(["STALE","CLOSED"].includes(providerFreshness as string)&&["READY_TO_APPLY","FILLED"].includes(from as string)){to="BLOCKED"; reason=`stale_closed_deactivates_queue_${providerFreshness}`; evidenceBinding=hasAnyLocal?"local":"none"; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason=`posting_${providerFreshness}_deactivates_queue_without_erasing_history`; app.execution.last_transition_at=now;}
        }else if(providerFreshness==="BLOCKED"&&from==="SUBMITTED"){to="BLOCKED"; reason="verification_BLOCKED_blocks_SUBMITTED"; conflict=true; anyConflict=true; evidenceBinding=hasAnyProvider?"provider":hasAnyLocal?"local":"none"; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason="verification_BLOCKED"; app.execution.last_transition_at=now;}
        }else{
          const channel=(app.execution?.channel as Channel)??providerApp.execution?.channel??"web_form"; const wantsSubmitted=providerApp.execution?.state==="SUBMITTED"||from==="SUBMITTED"; const isEmail=channel==="email"; let emailGuardPassed=true;
          if(isEmail&&wantsSubmitted){const mail=providerApp.mail; const operatorConfirmed=providerApp.operator_confirmed===true; const hasSent=mail?(mail.sent===true||mail.provider_confirmation==="sent"||mail.outbox===true):false; if(!hasSent&&!operatorConfirmed){emailGuardPassed=false; if(from==="SUBMITTED"){conflict=true; anyConflict=true; to="AWAITING_OPERATOR"; reason="draft_email_requires_sent_confirmation"; evidenceBinding=hasAnyLocal?"local":"none"; if(app.execution){app.execution.state="AWAITING_OPERATOR"; app.execution.awaiting_reason="draft_not_sent_requires_provider_confirmation_or_operator"; app.execution.last_transition_at=now;}}else{to=from==="FILLED"?"FILLED":"AWAITING_OPERATOR"; reason="email_draft_not_sent_requires_confirmation"; evidenceBinding=hasAnyProvider?"provider":hasAnyLocal?"local":"none";}}}
          if(emailGuardPassed){
            if(wantsSubmitted){const hasQualifying=hasProviderQual||hasLocalQual||providerApp.operator_confirmed===true; if(!hasQualifying){to=from==="FILLED"?"FILLED":from==="READY_TO_APPLY"?"READY_TO_APPLY":"AWAITING_OPERATOR"; reason="SUBMITTED_requires_qualifying_evidence"; evidenceBinding="none"; if(hasLocalQual&&!hasProviderQual){conflict=true; anyConflict=true;}
              }else{const providerStronger=hasProviderQual&&(!hasLocalQual||providerQual.length>=localQual.length); const localStronger=hasLocalQual&&!hasProviderQual; if(providerStronger){to="SUBMITTED"; evidenceBinding=providerApp.operator_confirmed?"operator_confirmed":"provider"; reason="provider_qualifying_evidence_promotes_SUBMITTED"; if(hasLocalQual&&providerQual[0]?.id!==localQual[0]?.id){conflict=true; anyConflict=true;} if(app.execution){app.execution.state="SUBMITTED"; app.execution.evidence_id=providerQual[0]?.id??app.execution.evidence_id??localQual[0]?.id; app.execution.last_transition_at=providerApp.execution?.last_transition_at??now; if(!app.submitted_at) app.submitted_at=now; if(!app.external_reference) app.external_reference=`provider-${providerSnapshot!.provider_id}-${app.id}`;}else{app.execution={state:"SUBMITTED",channel,last_transition_at:providerApp.execution?.last_transition_at??now,evidence_id:providerQual[0]?.id??localQual[0]?.id,detail:"provider reconciliation promoted to SUBMITTED"}; if(!app.submitted_at) app.submitted_at=now;} for(const pev of providerQual) if(!reconciledState.evidence.some(e=>e.id===pev.id)) reconciledState.evidence.push({id:pev.id,application_id:app.id,kind:pev.kind,artifact:{owner:"user",kind:"relative_path",locator:`evidence/${app.id}/${pev.id}.txt`},observed_at:pev.observed_at});}
                else if(localStronger){to=from==="SUBMITTED"?"SUBMITTED":"FILLED"; evidenceBinding="local"; reason="local_qualifying_preserved_conflict"; if(hasProviderQual){conflict=true; anyConflict=true;}}
                else{to="SUBMITTED"; evidenceBinding=hasProviderQual?"provider":"local"; reason="conflict_preserved_keep_stronger"; conflict=true; anyConflict=true;}}
            }else{to=from; if(hasAnyLocal&&!hasAnyProvider){evidenceBinding="local"; reason="local_export_remains_local_until_reconciled";}else if(hasAnyProvider){evidenceBinding="provider"; reason="provider_evidence_available"; if(hasLocalQual&&providerQual[0]?.id!==localQual[0]?.id){conflict=true; anyConflict=true; evidenceBinding="provider"; reason="conflict_preserved_provider_stronger";}else if(hasAnyLocal&&providerAny[0]?.id!==localAny[0]?.id){conflict=true; anyConflict=true;}}else{evidenceBinding="none"; reason="no_qualifying_evidence";} if(["STALE","CLOSED"].includes(oppVerification as string)&&["READY_TO_APPLY","FILLED"].includes(from as string)){to="BLOCKED"; reason=`freshness_${oppVerification}_deactivates_queue`; if(app.execution){app.execution.state="BLOCKED"; app.execution.block_reason=`posting_${oppVerification}`; app.execution.last_transition_at=now;}}}
          }
        }
      }
    }
    if(providerApp?.operator_confirmed) evidenceBinding="operator_confirmed";
    execution.push({application_id:app.id,from,to,evidence_binding:evidenceBinding,conflict_preserved:conflict,reason}); if(to!==from&&app.execution&&app.execution.state!==to) app.execution.state=to as ExecutionState; if(conflict) anyConflict=true;
  }
  let overall:ReconciliationResult["evidence_binding"]="none"; if(execution.some(e=>e.evidence_binding==="operator_confirmed")) overall="operator_confirmed"; else if(execution.some(e=>e.evidence_binding==="provider")) overall="provider"; else if(execution.some(e=>e.evidence_binding==="local")) overall="local";
  const result:ReconciliationResult={schema:RECONCILIATION_SCHEMA,reconciled_at:now,provider_read_back:providerReadBack,freshness_transition:freshness,execution_transition:execution,evidence_binding:overall,conflict_preserved:anyConflict,queue_active:queueActive,history_preserved:historyPreserved,idempotent:true};
  const hasFresh=freshness.some(f=>f.from!==f.to); const hasExec=execution.some(e=>e.from!==e.to); const hasChanges=hasFresh||hasExec||anyConflict; if(hasChanges&&JSON.stringify(careerState)!==JSON.stringify(reconciledState)){reconciledState.revision=(reconciledState.revision??0)+1; reconciledState.updated_at=now;}
  return {reconciledState,result};
}
export function isIdempotent(careerState:CareerState,snapshot:ProviderSnapshot){const f=reconcile(careerState,snapshot); const s=reconcile(f.reconciledState,snapshot); return JSON.stringify(f.reconciledState)===JSON.stringify(s.reconciledState);}
export function requiresProviderReadBack(s:ProviderSnapshot|null|undefined){return !s||s.read_back!==true;}
